version: '3'

services:
  app:
    build: app
    ports:
      - "80:80"
    container_name: front-container
    restart: always
    depends_on:
      - api
  api:
    build: api
    ports:
      - "3000:3000"
    container_name: back-container
    restart: always
