FROM node:8 AS node

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN npm install --verbose

COPY --chown=node:node . .

RUN npm run build --prod

FROM nginx

COPY --from=node /home/node/app/dist /usr/share/nginx/html/
COPY docker/nginx-conf/ /etc/nginx/conf.d/

EXPOSE 80